In [1]:
import torch

# torch.topk():沿给定dim维度返回输入张量input中的k个最大值。如果不指定dim,则默认为input的最后一维
# 返回一个元组(values,indices),其中indices是原始输入张量input中元素下标。

test_tensor = torch.randn(3,4)

In [2]:
test_tensor

tensor([[ 0.0902, -1.5790, -0.3043,  0.5388],
        [ 0.5620, -1.4187, -1.1626,  1.0433],
        [-1.4488,  0.3836, -2.5095, -1.4731]])

In [16]:
values,indices = test_tensor.topk(2)

In [17]:
values.size()

torch.Size([3, 2])

In [18]:
values.type()

'torch.FloatTensor'

In [19]:
indices.size()

torch.Size([3, 2])

In [20]:
indices.type()

'torch.LongTensor'

In [21]:
indices

tensor([[3, 0],
        [3, 0],
        [1, 0]])

&emsp;&emsp;假设input size为[batch_size,hidden_size,seq_len],k=2,那么返回的如下

- values: [batch_size,hidden_size,k]
- indices: [batch_size,hidden_size,k] type为torch.LongTensor，其中是有顺序的

In [22]:
values

tensor([[ 0.5388,  0.0902],
        [ 1.0433,  0.5620],
        [ 0.3836, -1.4488]])