#### word attention

&emsp;&emsp;不是每个单词对整句话的重要程度是相同的，学习一下每个单词的不同重要程度,需要注意一下，需要找出pad的单词，trick

$$u_t = tanh(W_w*h_t + b_w) \tag{1}$$

$$\alpha_t = \frac{exp(u_t^{T} * u_w)}{\sum_{t^{,}}{exp(u_{t^{,}}^T u_w)}} \tag{2}$$

$$s_i = \sum_{t}\alpha_t h_t \tag{3}$$

&emsp;&emsp;$W_w,b_w$是计算每个单词权重的参数，通过训练学习，$u_w$表示上下文向量，是在训练的过程中学习获得的，可以将$u_w$当作一种询问的高级表示

In [1]:
import torch

input_test = torch.tensor([[1,4,0],[3,2,0]])

In [2]:
input_test.type()

'torch.LongTensor'

In [8]:
input_test

tensor([[1, 4, 0],
        [3, 2, 0]])

In [9]:
mask = torch.ones_like(input_test)

In [10]:
mask

tensor([[1, 1, 1],
        [1, 1, 1]])

In [11]:
mask[input_test==0]=0

In [12]:
mask

tensor([[1, 1, 0],
        [1, 1, 0]])

In [13]:
input_test==0

tensor([[False, False,  True],
        [False, False,  True]])

In [14]:
import torch.nn as nn

vocab_size = 10
embedding_dim = 3
hidden_dim = 4

embedding = nn.Embedding(vocab_size,embedding_dim)
input_tensor = torch.LongTensor([[2,4,6,0,0],[3,7,5,6,0]])

In [15]:
mask = input_tensor!=0

In [17]:
mask

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True, False]])

In [18]:
weight_w = torch.ones(embedding_dim,embedding_dim)

In [21]:
x1 = torch.Tensor([[2,3,4],[5,6,7]])
x2 = torch.Tensor([[3],[5]])
x1 * x2

tensor([[ 6.,  9., 12.],
        [25., 30., 35.]])