In [10]:
import torch
from torch import nn

input_test = torch.zeros(3,5)

In [11]:
input_test

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [12]:
nn.init.uniform_(input_test, -0.1, 0.1)

tensor([[ 0.0091,  0.0652, -0.0050,  0.0806, -0.0441],
        [-0.0614,  0.0016, -0.0805, -0.0192,  0.0722],
        [-0.0700,  0.0992, -0.0613,  0.0874, -0.0246]])

In [13]:
input_test

tensor([[ 0.0091,  0.0652, -0.0050,  0.0806, -0.0441],
        [-0.0614,  0.0016, -0.0805, -0.0192,  0.0722],
        [-0.0700,  0.0992, -0.0613,  0.0874, -0.0246]])

In [20]:
import numpy as np
input1 = torch.empty(2,2,2)

In [21]:
input1

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 4.6566e-10],
         [0.0000e+00, 4.6566e-10]]])

In [22]:
inpu2 = torch.empty(2,2,1)

In [23]:
torch.cat((input1,inpu2),dim=2)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 4.6566e-10]],

        [[0.0000e+00, 4.6566e-10, 3.4913e-13],
         [0.0000e+00, 4.6566e-10, 2.5250e-29]]])